---
language: python
services: docker

env:
  global:
    - MOLECULE_PROJECT_DIR: "$TRAVIS_BUILD_DIR"
    - MOLECULE_ROLE_NAME: "$(basename $TRAVIS_BUILD_DIR)"
    - HCLOUD_TOKEN: "$HCLOUD_TOKEN"
    - MOLECULE_TEST_SCOPE: "$TRAVIS_BUILD_ID"

before_script:
  - wget https://raw.githubusercontent.com/infrastructr/docker-molecule/master/docker-compose.yml
  - docker-compose up -d

script:
  - docker-compose exec -e HCLOUD_TOKEN="$HCLOUD_TOKEN" -e MOLECULE_TEST_SCOPE="$MOLECULE_TEST_SCOPE" molecule molecule test --all

after_script:
  - docker-compose down

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
