---
- name: Verify WireGuard state
  hosts: all
  tasks:
    - name: Get WireGuard service status
      command: wg
      register: service_status
      changed_when: no
    - name: Verify WireGuard is running and listening to the port
      assert:
        that:
          - "'listening' in service_status.stdout"
          - "'{{ wireguard_port }}' in service_status.stdout"
